---
title: "Basic"
author: "Juhong Park"
---

# Variable Assignment
```{r}
x <- 1
x
```

# Variable Print
```{r}
x <- "Hello World"
print(x)  # Print Function
x <- "Hello World"
x  # Auto Print
```

# Atomic Class
```{r}
x <- "x"
class(x)
x <- 3
class(x)
x <- c(1, 2)
class(x)
x <- 3L
class(x)
x <- 1:2
class(x)
x <- 3+14i
class(x)
x <- TRUE
class(x)
```

# Vector
```{r}
x <- 1:4
x
x <- c(1:4)
x
x <- c(1, 2, 3, 4)
x
x <- c("One", "Two", "Three", "Four")
x
x <- vector("numeric", length=4)
x
```

### Vector Operation
```{r}
x <- c(1:4)
x
y <- c(5:8)
y
x + y
x - y
x * y
x / y
z <- c(9:10)
x + y  # Recycling
```

# Coercion
### Implicit Coercion
```{r}

x <- c("One", 2, "Three", 4)
x
x <- c("TRUE", TRUE)
x
x <- c(1, TRUE)
x
```

### Explicit Coercion
```{r}
x <- 1:4
x
as.character(x)
x <- c("1", "2", "3", "4")
x
as.numeric(x)
```

### Coercion Error
```{r}
x <- c("One", "Two", "Three", "Four")
x
as.numeric(x)
```

# List
```{r}
x <- list(1, "1", TRUE)
x  # Doule Bracket for List
sapply(x, class)
x <- c(1, "1", TRUE)
x  # Single Bracket for Vector
sapply(x, class)
```

# Matrix
### Matrix by Vector
```{r}
x <- matrix(1:12, nrow=3, ncol=4)
x
dim(x)
attributes(x)
x <- 1:12
x
dim(x) <- c(3, 4)
x
```

### Matrix by Bind
```{r}
x <- 1:3
y <- 4:6
cbind(x, y)
rbind(x, y)
```

### Implicit Coercion of Matrix
```{r}
x <- 1:3
y <- c("4", "5", "6")
cbind(x, y)
```

### Matrix Operation
```{r}
x <- matrix(1:4, 2, 2)
x
y <- matrix(5:8, 2, 2)
y
x + y
x - y
x * y
x / y
x %*% y
```

# Factor
```{r}
x <- factor(c("Up", "Down", "Down", "Up", "Down"))
x
table(x)
unclass(x)
x <- factor(c("Up", "Down", "Down", "Up", "Down"), levels=c("Up", "Down"))
x
```

# Missing Value
```{r}
x <- c(0/0, NaN, NA)
x
is.nan(x)  # NaN: Not a Number
is.na(x)  # NA: Not Availalbe
```

# Data Frame
```{r}
x <- data.frame(num=1:3, word=c("Four", "Five", "Six"))
x
nrow(x)
ncol(x)
```

# Names
```{r}
x <- 1:2
x
names(x)
names(x) <- c("First", "Second")
x
x <- list(Three=3, Four=4)
x
```